import { CHAINS, GasToken } from "@axelar-network/axelarjs-sdk";

const chainInfo: { [key: string]: [string, string] } = {
  "5": [CHAINS.TESTNET.ETHEREUM, GasToken.ETH],
  "43113": [CHAINS.TESTNET.AVALANCHE, GasToken.GLMR],
  "4002": [CHAINS.TESTNET.FANTOM, GasToken.FTM],
  "80001": [CHAINS.TESTNET.POLYGON, GasToken.MATIC],
  "1287": [CHAINS.TESTNET.MOONBEAM, GasToken.GLMR],
  "1313161555": [CHAINS.TESTNET.AURORA, GasToken.AURORA],
  "97": [CHAINS.TESTNET.BINANCE, GasToken.BINANCE],
  "421613": [CHAINS.TESTNET.ARBITRUM, GasToken.ETH],
  "44787": [CHAINS.TESTNET.CELO, GasToken.CELO],
  "2221": [CHAINS.TESTNET.KAVA, GasToken.KAVA],
  "84531": [CHAINS.TESTNET.BASE, GasToken.BASE],
  "314159": [CHAINS.TESTNET.FILECOIN, GasToken.FILECOIN],
  "420": [CHAINS.TESTNET.OPTIMISM, GasToken.ETH],
  "59140": [CHAINS.TESTNET.LINEA, GasToken.ETH],
}

export default chainInfo;
